# Basic Site Settings
title         : "Shivani Yadav"
logo          : "/images/profile pic.png"
name          : "Shivani Yadav"
description   : "Post Graduate Student pursuing Masters in Business Analytics from University of Cincinnati."
  
theme: jekyll-theme-minimal

#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
